name: VitalCondense
version: @version@
main: com.tamrielnetwork.vitalcondense.VitalCondense
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to condense items in their inventory.
commands:
  vitalcondense:
    description: "Main command"
    usage: "/vitalcondense"
permissions:
  vitalcondense.condense:
    description: "Permission to toggle crafting interface"
    default: op